### ISSUE TITLE
client

### ISSUE THREAD

**Issue by nekbre221** [letannadine/groupes10.py#6]
`class Client:
   
 def __init__(self, nom, prénom, âge, adresse):#consructeur de clients
        print("")   
        print("     ****CREATION D'UN NOUVEAU CLIENT DE LA BANQUE****")
        self.nom = nom
        self.prénom = prénom
        self.âge = âge
        self.adresse = adresse
        print("")
        print("    * informations personnelles du client *")
        
c1 = Client("ALIMATOU", "BOUBAKARI", 45, "ngaoundéré")#objet c1
print("")
print(" Nom du client: "+c1.nom)#concaaténation
print(" Prénom du client: "+c1.prénom)
print(" Âge du client: {}".format(c1.âge)+" ans")#limite de la concaténation car pas possible entre string et int passsons aux textes préformaté
print(" Adresse du client: "+c1.adresse)     

def ajouteCompte(self,compte):
    self.__mesComptes.append(compte)
    compte.assigneTitulaire(self)
    
def identifieCompte(self):#elle dépendra de la classe compte 
    print ("Sur quel compte ?")
    x=input("?")
    for c in self.__mesComptes:
        if c.donneNumero() == x:
            return c
    
def emprunt(self):
    c=self.identifieCompte()
    print ("quel montant ?")
    x=int(input("?"))
    c.retire(x)
    
def depose(self):
    c=self.identifieCompte()
    print ("quel montant ?")
    x=int(input("?"))
    c.depose(x)`

**Comment by McGarsay** [comment]
Génial
